routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/alterarsenha', 'UserController@alterarsenhaIndex');

Route::post('/alterarsenha', 'UserController@alterarsenha');
 
Route::get('/', 'HomeController@index')->middleware('auth');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::post('/cadastrar', 'Auth\LoginController@cadastro');

Route::get('/cadastro/curriculos', 'CurriculoController@index');
Route::post('/cadastro/curriculos/filtrar', 'CurriculoController@filtrar');
Route::get('/cadastro/curriculos/{id}/edicao', 'CurriculoController@formulario');
Route::get('/cadastro/curriculos/{id}/visualizar', 'CurriculoController@visualizar');
Route::get('/cadastro/curriculos/{id}/exportar', 'CurriculoController@exportar');
Route::get('/cadastro/curriculos/moreHistory', 'CurriculoController@novoHistorico');
Route::post('/cadastro/curriculos/salvar', 'CurriculoController@salvar');
Route::get('/cadastro/curriculos/{id}/loadCurriculo', 'CurriculoController@loadCurriculo');

Route::get('/cadastro/usuarios', 'UserController@index');
Route::post('/cadastro/users/filtrar', 'UserController@filtrar');
Route::post('/cadastro/users/salvar', 'UserController@salvar');
Route::post('/cadastro/users/formById', 'UserController@formById');
Route::get('/cadastro/usuarios/{id}/edicao', 'UserController@formulario');

Route::get('/cadastro/empresas', 'EmpresaController@index');
Route::post('/cadastro/empresas/filtrar', 'EmpresaController@filtrar');
Route::post('/cadastro/empresas/salvar', 'EmpresaController@salvar');
Route::post('/cadastro/empresas/formById', 'EmpresaController@formById');
Route::get('/cadastro/empresa/{id}/edicao', 'EmpresaController@formulario');

Route::get('/cadastro/actuations', 'ActuationController@index');
Route::post('/cadastro/actuations/filtrar', 'ActuationController@filtrar');
Route::get('/cadastro/actuations/{id}/quickModal', 'ActuationController@quickModal');
Route::post('/cadastro/actuations/viability', 'ActuationController@viability');
Route::post('/cadastro/actuations/salvar', 'ActuationController@salvar');
Route::get('/cadastro/actuations/{id}/changeStatus', 'ActuationController@changeStatus');
Route::get('/cadastro/actuations/{id}/deletar', 'ActuationController@deletar');

Route::get('/cep/{cep}/encontracep', 'CepController@encontraCep');

Route::get('/vagas', 'VagaController@index');
Route::get('/vagas/{id}/edicao', 'VagaController@formulario');
Route::post('/vagas/salvar', 'VagaController@salvar');
Route::post('/vagas/filtrar', 'VagaController@filtrar');
Route::post('/vagas/filtrarCandidato', 'VagaController@filtrarCandidatos');
Route::get('vagas/{id}/view', 'VagaController@view');
Route::get('/vagas/encontrar', 'VagaController@encontrar');
Route::post('/vagas/candidatar', 'OcupacaovagaController@candidatar');
Route::get('vagas/{id}/candidatos', 'VagaController@viewCandidatos');

Route::get('/vagas/requisicao-pessoal/vaga/{vaga}', 'VagaController@emitirRequisicao')->name('vagas_requisicao');

Route::get('/vagasintegradas', 'VagaController@indexVagaIntegrada');
Route::post('/vagasintegradas/filtrar', 'VagaController@filtrarIntegrada');
Route::post('/vagasintegradas/toggleApiAvailable', 'VagaController@toggleApiAvailable');

Route::get('/teste/{vagas}', 'VagaController@gerarBoleto');

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use App\Helpers\CustomFuncs;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\PasswordReset;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getDataNascimentoAttribute($value){
        try{
            if($value == null){
                return null;
            }
            return Carbon::parse($value)->format('d/m/Y');
        } catch (\Exception $e) {
            return $value;
        }
    }

    public function perfil(){
        return $this->hasOne('App\Models\Perfisusuario', 'id', 'perfisusuario_id');
    }

    public function uf(){
        return $this->hasOne('App\Models\Uf', 'id', 'uf_id');
    }

    public function curriculo(){
        return $this->hasOne('App\Models\Curriculo', 'user_id');
    }

    public function escolaridade(){
        return $this->hasOne('App\Models\Escolaridade', 'id', 'escolaridade_id');
    }

    public function sexo(){
        return $this->hasOne('App\Models\Sexo', 'id', 'sexo_id');
    }

    public function civilstate(){
        return $this->hasOne('App\Models\Civilstate', 'id', 'civilstate_id');
    }

    public function empresas(){
        return $this->hasMany('App\Models\Empresa', 'criador_id');
    }

    public function fullAddress(){
        $rua = $this->logradouro;
        $numero = $this->numero;
        $complemento = $this->complemento;
        $cidade = $this->cidade;
        $uf = $this->uf != null ? $this->uf->sigla : null;

        if($this->cep == null){
             $fullAddress = "Não registrado";
        } else {
            $fullAddress = $rua;
            if($numero != null){
                $fullAddress = $fullAddress.", ".$numero;
            }

            $fullAddress = $fullAddress." - ".$cidade.",".$uf;

            if($complemento != null){
                $fullAddress = $fullAddress." (".$complemento.")";
            }
        }


        return $fullAddress;
    }

    public function fullContato(){
        return CustomFuncs::formatarCelular($this->celular)." ".$this->email;
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new PasswordReset($token));
    }
}

resources/views/cadastro/usuarios/_form.blade.php
@php
    $isCandidato = (Auth::user() != null && Auth::user()->perfil->identificador == "Candidato");
@endphp
<input type="hidden" id="userId" value="{{ $user->id }}" />
<div class="row">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label>Nome</label>
                    <input type="text" class="form-control" name="nome" id="nome" placeholder="Nome completo" value="{{ $user->nome }}" required/>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- <div class="col-md-6">
                <div class="form-group">
                    <label>Login</label>
                    <input type="text" class="form-control" name="login" id="login" placeholder="Login" value="{{ $user->login }}" {{ $user->login == null ? '' : 'disabled' }} required/>
                </div>
            </div> -->
            <div class="col-md-6">
                <div class="form-group">
                    <label>CPF</label>
                    <input type="text" class="form-control" name="cpf" id="cpf" placeholder="CPF" value="{{ $user->cpf }}" data-inputmask='"mask": "999.999.999-99", "clearIncomplete" : true' data-mask {{ $user->cpf == null ? '' : 'disabled' }} required/>
                </div>
            </div>
        </div>
        @if(!$isCandidato)
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label>Senha</label>
                    <input type="password" class="form-control" name="password" id="password" placeholder="Senha" {{ $user->password != null ? 'disabled' : '' }}/>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Confirme a senha</label>
                    <input type="password" class="form-control" name="confirmPassword" id="confirmPassword" placeholder="Confirme a senha" {{ $user->password != null ? 'disabled' : '' }}/>
                </div>
            </div>
            <div class="col-md-4">
                <div class="checkbox" style="margin-top: 25px">
                  <label><input type="checkbox" id="confirmChange" name="confirmChange" value="" onchange="hotsite.user.activePassword(this)" {{ $user->password == null ? 'disabled checked' : '' }}>Alterar senha?</label>
                </div>
            </div>
        </div>
        @endif
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Email</label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="E-mail" value="{{ $user->email }}" required/>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Estado Civil</label>
                    <select class="form-control select2" name="civilstate" id="civilstate" style="width: 100%;">
                        <option value="nd" {{ $user->civilstate_id == '' ? 'selected' : '' }}>Não informado</option>
                        {{info($user->civilstate_id)}}
                        @foreach($civilstates as $civilstate)
                            <option value="{{$civilstate->id}}" {{ $user->civilstate_id == $civilstate->id ? 'selected' : '' }}>{{$civilstate->descricao}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label>Sexo</label>
                    <select class="form-control select2" name="sexo" id="sexo" data-placeholder="Sexo" style="width: 100%;" required>
                        @foreach($sexos as $sexo)
                            <option value="{{$sexo->id}}" {{ $user->sexo_id == $sexo->id ? 'selected' : '' }}>{{$sexo->descricao}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Data de Nascimento</label>
                    <input type="text" class="form-control" name="dataNascimento" id="dataNascimento" value="{{ $user->data_nascimento }}" required />
                </div>
            </div>
            @if(!$isCandidato)
            <div class="col-md-4">
                <div class="form-group">
                    <label>Perfil</label>
                    <select class="form-control select2" name="perfil" id="perfil" data-placeholder="Perfil" style="width: 100%;" required>
                        @foreach($perfis as $perfil)
                            <option value="{{$perfil->id}}" {{ $user->perfisusuario_id == $perfil->id ? 'selected' : '' }}>{{$perfil->descricao}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            @else
                <input type="hidden" id="perfil" id="perfil" value="{{ $perfis->where('identificador','=','Candidato')->first()->id }}" />
            @endif
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Escolaridade</label>
                    <select class="form-control select2" name="escolaridade" id="escolaridade" data-placeholder="Escolaridade" style="width: 100%;" required>
                        @foreach($escolaridades as $escolaridade)
                            <option value="{{$escolaridade->id}}" {{ $user->escolaridade_id == $escolaridade->id ? 'selected' : '' }}>{{$escolaridade->descricao}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Formação</label>
                    <input type="text" class="form-control" name="formacao" id="formacao" value="{{ $user->formacao }}" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Telefone</label>
                    <input type="text" class="form-control" name="telefone" id="telefone" value="{{ $user->telefone }}" data-inputmask='"mask": "(99) 9999-9999", "clearIncomplete" : true' data-mask/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Celular</label>
                    <input type="text" class="form-control" name="celular" id="celular" value="{{ $user->celular }}" data-inputmask="'mask': '(99) 99999-9999', 'clearIncomplete' : true" data-mask/>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>CEP <i class="fa fa-question-circle" title="CEP incorreto" id="cepError" style="display: none"></i></label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="cep" id="cep" value="{{ $user->cep }}" data-inputmask='"mask": "99999-999", "clearIncomplete" : true' data-mask required/>
                        <span class="input-group-btn">
                            <button class="btn btn-primary" onclick="hotsite.buscaCep('cep', this)"><i class="fa fa-search"></i> Buscar CEP</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7">
                <div class="form-group">
                    <label>Logradouro <i class="fa fa-question-circle" title="Preenchido pelo CEP"></i></label>
                    <input type="text" class="form-control" name="logradouro" id="logradouro" value="{{ $user->logradouro }}" required disabled/>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label>Número</label>
                    <input type="text" class="form-control" name="numero" id="numero" value="{{ $user->numero }}" required/>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label>Complemento</label>
                    <input type="text" class="form-control" name="complemento" id="complemento" value="{{ $user->complemento }}" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
                <div class="form-group">
                    <label>Bairro <i class="fa fa-question-circle" title="Preenchido pelo CEP"></i></label>
                    <input type="text" class="form-control" name="bairro" id="bairro" value="{{ $user->bairro }}" disabled required/>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Cidade <i class="fa fa-question-circle" title="Preenchido pelo CEP"></i></label>
                    <input type="text" class="form-control" name="cidade" id="cidade" value="{{ $user->cidade }}" disabled required/>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label>UF <i class="fa fa-question-circle" title="Preenchido pelo CEP"></i></label>
                    <select class="form-control select2" name="uf" id="uf" data-placeholder="UF" style="width: 100%;" disabled>
                        <option value=""></option>
                        @foreach($ufs as $uf)
                            <option value="{{$uf->id}}" {{ $user->uf_id == $uf->id ? 'selected' : '' }}>{{$uf->sigla}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/cadastro/usuarios/_list.blade.php
<table class="table table-striped table-responsive">
    <thead>
        <tr>
          <th style="width: 10px">ID</th>
          <th>Nome</th>
          <th>CPF</th>
          <th>Contato</th>
          <th>Endereço</th>
          <th>Perfil</th>
          <th></th>
        </tr>
    </thead>
    <tbody>
    	@foreach($users as $user)
			<tr>
				<td>{{$user->id}}</td>
				<td>{{$user->nome}}</td>
				<td>{{CustomFuncs::formatarCpf($user->cpf)}}</td>
				<td>{{$user->fullContato()}}</td>
				<td>{{$user->fullAddress()}}</td>
				<td>{{$user->perfil->descricao}}</td>
				<td>
					<a href="/cadastro/usuarios/{{ $user->id }}/edicao">
						<i class="fa fa-edit"></i>
					</a>
				</td>
			</tr>
			@endforeach
    </tbody>
</table>

<div class="pagination-area">
{{ $users->links() }}
</div>



<script>
	$(document).ready(function() {
	    $('.pagination a').on('click', function (event) {
	        event.preventDefault();
	        if ( $(this).attr('href') != '#' ) {
	            url = $(this).attr('href');
	            page = url.split('page=')[1];
	            $('#pagina').val(page);
	            hotsite.user.filtrar(page);
	        }
	    });
	  });
</script>

resources/views/cadastro/usuarios/changepassword.blade.php
@extends('layouts.appinterno')

@section('content')
<section class="content-header">
  <h1>
    Usuário
    <small>
        Alterar minha senha
    </small>
</h1>  
</section>
<section class="content">
    @csrf
    <div class="row">
        <div class="col-xs-12 col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Alterar senha</h3>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Senha</label>
                                <input type="password" class="form-control" name="password" id="password" placeholder="Digite sua senha" value="" required/>
                            </div>                        
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Confirmar senha</label>
                                <input type="password" class="form-control" name="confirmPassword" id="confirmPassword" placeholder="Confirme a senha" value="" required/>
                            </div>                        
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <button class="btn btn-primary pull-right" onclick="hotsite.user.changePassword()">Alterar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection


@section('scripts')
<script src="{{ asset('js/hotsite/Hotsite.User.js') }}"></script>
<script>
    $('.select2').select2();
    $('[data-mask]').inputmask();
    hotsite.user.filtrar();
</script>
@endsection

resources/views/cadastro/usuarios/formMain.blade.php
@extends('layouts.appinterno')

@section('content')
<section class="content-header">
  <h1>
    Usuário
    <small>Formulário</small>
    <div class="pull-right">
        <a class="btn btn-flat btn-primary" href="{{ URL::previous() }}"><i class="fa fa-arrow-left"></i> Voltar</a>
    </div>
</h1>  
</section>
<section class="content">
    @csrf
    <div class="row">
	    <div class="col-xs-12 col-md-12">
	        <div class="box box-primary">
	            <div class="box-header with-border">
	                <h3 class="box-title">Informações do usuário</h3>
	                <div class="box-tools pull-right">
	                </div>
	            </div>
	            <div class="box-body">
	    			@include('cadastro.usuarios._form')
	    		</div>
	        </div>
	    </div>
	</div>
    <div class="row">
        <div class="col-md-12">
            <button class="btn btn-primary pull-right" onclick="hotsite.user.salvar(false)">
                <i class="fa fa-save"></i> Salvar
            </button>
        </div>
    </div>
</section>

@endsection


@section('scripts')
    <script src="{{ asset('js/hotsite/Hotsite.User.js') }}"></script>
    <script>
        $('.select2').select2();
	    $('#dataNascimento').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' });
	    $('[data-mask]').inputmask();
    </script>
@endsection

resources/views/cadastro/usuarios/index.blade.php
@extends('layouts.appinterno')

@section('content')
<section class="content-header">
  <h1>
    Usuário
    <small>
        @if(Auth::user()->perfil->identificador == "Candidato")
            Meu perfil
        @else
            Todos usuários
        @endif
    </small>
</h1>  
</section>
<section class="content">
    @csrf
    <div class="row" style="display: {{ Auth::user()->perfil->identificador == 'Candidato' ? 'none' : '' }}">
        <div class="col-xs-12 col-md-12">
            <div class="box box-primary collapsed-box">
                <div class="box-header with-border">
                    <h3 class="box-title">Filtros</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Nome</label>
                                <input type="text" class="form-control" name="name" id="name" />
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>CPF</label>
                                <input type="text" class="form-control" name="cpf" id="cpf"  data-inputmask='"mask": "999.999.999-99"' data-mask/>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Perfil</label>
                                <select class="form-control select2" name="perfis[]" id="perfis" multiple="multiple" data-placeholder="Escolha os perfis"
                                style="width: 100%;">
                                    @foreach($perfis as $perfil)
                                        <option value="{{$perfil->id}}">{{$perfil->descricao}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <div class="col-md-12">
                        <button class="btn btn-primary pull-right" onclick="hotsite.user.filtrar()">
                            <i class="fa fa-search"></i> Filtrar
                        </button>
                    </div>
                </div>

            </div>
        </div>
    </div>
<div class="row">
    <div class="col-xs-12 col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">{{ Auth::user()->perfil->identificador == "Candidato" ? 'Meu perfil' : 'Lista de usuários' }}</h3>
                <div class="box-tools pull-right">
                    @if(Auth::user()->perfil->identificador != "Candidato")
                    <a href="/cadastro/usuarios/new/edicao" class="btn btn-box-tool btn-box-tool-add"><i class="fa fa-plus"></i> Novo usuário
                    </a>
                    @endif
                    
                </div>
            </div>
            <div class="box-body no-padding">
                <div class="overlay" style="display: block">
                    <i class="fa fa-refresh fa-spin"></i>
                </div>
                <div id="result"></div>
            </div>
            <!-- <div class="box-footer clearfix"> -->
                <!-- <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">&laquo;</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">&raquo;</a></li>
                </ul> -->
            <!-- </div> -->
        </div>
    </div>
</div>
</section>

@endsection


@section('scripts')
<script src="{{ asset('js/hotsite/Hotsite.User.js') }}"></script>
<script>
    $('.select2').select2();
    $('[data-mask]').inputmask();
    hotsite.user.filtrar();
</script>
@endsection